### ISSUE TITLE
Why IDE not file exe ?

### ISSUE THREAD

**Issue by anhtran1989** [RoyalShield/royalshield-ide#1]
Hi, i see framework of you very good, i want learn. You can answer question of me. 
1. I download IDE of you but not open, why it's not file .EXE
2. How long you write doc :D :D
Thanks you. Sorry my english :(

**Comment by avuenja** [comment]
Yo, here's the answer to your first question:
The IDE does not work as an .exe but a .air, you need Adobe Air to install it
https://get.adobe.com/air/

**Comment by Mignari** [comment]
Hi, anhtran1989, the doc will be written progressively, because my english is not good as well XD
